{% set name = "sqlite-utils" %}
{% set version = "3.22.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sqlite-utils-{{ version }}.tar.gz
  sha256: 35ebb4f7e2b09f1818b36e7da6dc62f1ca57e2c0d99a9cbc8151e634d75a7906

build:
  entry_points:
    - sqlite-utils = sqlite_utils.cli:cli
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - click
    - click-default-group
    - dateutils
    - python >=3.6
    - sqlite-fts4
    - tabulate

test:
  source_files:
    - tests
  imports:
    - sqlite_utils
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - cogapp
    - hypothesis
    - pip
    - pytest

about:
  home: https://github.com/simonw/sqlite-utils
  summary: CLI tool and Python utility functions for manipulating SQLite databases
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
